# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f9d14fecbbd03c3d52652839a01554a4842044d42def17f6c8d4da8532b94fb3e969290050337387c2b3e833a8d7e402d941f2dbaf0a87e5cbebf2755e03f93

test:
  secret_key_base: 6340c95f07b4881a4b5564bba2acbf2c9941618715e039274810daf4c78e9b880f55e1b1822d85c4511504e090e0646c39040b6621f1db85b88d006275374f8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
